# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b5cd6856dd6fd2c60b15745f752184297c587552548731ab4ad3306c1f2922fb1f4cbe133e1332397c25df28793b265fede563d8b2a66f1614186dc2bf3079d

test:
  secret_key_base: e0fecff26311d0fdd7dc54ada2b5d7f26e17b2def5de5ba34b12dcd9fb544c016a2225bf53b8b88e087be447f2df6a1310bb6cd848647baceb007808bc696a79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
